- name: Import secret ssh key file
  include_vars: "keys_vault.yml"
  no_log: true

- name: Write the content to a respective files.
  copy:
    content: "{{ item.value }}"
    dest: "~/.ssh/{{ item.key }}"
    mode: 0600
  with_dict: "{{ key_files }}"
  no_log: true

- name: Copy the ssh config file to the correct folder.
  copy:
    src: "../vars/config_vault"
    dest: "~/.ssh/config"
