alias g="git"
alias gci='git-checkout-issue'
alias gcm='git checkout master'
alias gdm='git diff master'
alias gp="git pull"
alias glm='git log ...master'
alias gs="git status"
alias gst="git status"
alias gsta='git add -A; git stash'
alias gstl='git stash list'
alias gstp='git stash pop'
