- name: Install Visual Studio Code Extensions
  command: code --install-extension {{item}}
  with_items: '{{vs_code_extensions}}'

- name: Install VS Code with Homebrew
  homebrew: name=visual-studio-code state=latest
  when: ansible_os_family == "Darwin"
