- name: Install VS Code with Homebrew
  homebrew_cask: name=visual-studio-code
  when: ansible_os_family == "Darwin"

- name: Install Visual Studio Code Extensions
  command: code --install-extension {{item}}
  with_items: '{{vs_code_extensions}}'
