
# Installation and setup
- include_tasks: "{{ ansible_os_family | lower }}.yml"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Change default shell to zsh
  command: chsh -s /usr/local/bin/zsh
  # Only run this if above task was changed
  when: zsh_shells.changed

- import_tasks: prezto.yml
  when: zsh_prezto

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
  when: not zsh_prezto
