- name: Install pyenv
  homebrew: name=pyenv state=latest

- name: Install lzlib
  homebrew: name=lzlib state=latest

- name: Install openssl
  homebrew: name=openssl state=latest

- name: Check if pytest.ini file exists
  stat: path="{{dotfiles_user_home}}/pytest.ini"
  register: pytest_stat

- name: Back up pytest.ini file
  command: mv ~/pytest.ini ~/pytest.ini.bak
  args:
    creates: "{{dotfiles_user_home}}/pytest.ini"
  when: pytest_stat.stat.exists

- name: Link pytest.ini file
  file:
    src: "{{dotfiles_home}}/roles/python_pyenv/files/pytest.ini"
    dest: "{{dotfiles_user_home}}/pytest.ini"
    state: link

# https://medium.com/@henriquebastos/the-definitive-guide-to-setup-my-python-workspace-628d68552e14
- import_tasks: python3.yml
- import_tasks: python2.yml

- name: "pipx: Upgrade all packages"
  command: "pipx upgrade-all"

- name: Set global pyenv path
  pyenv:
   subcommand: global
   versions:
     - "{{ latest_python_3_7.stdout }}"
     - "{{ latest_python_2_7.stdout }}"
