# Install visual studio code
osx_cask_packages:
  - visual-studio-code

# Install visual studio extensions.
vs_code_extensions:
  - PeterJausovec.vscode-docker
  - Shan.code-settings-sync
  - WallabyJs.quokka-vscode
  - Zignd.html-css-class-completion
  - christian-kohler.npm-intellisense
  - dbaeumer.vscode-eslint
  - dbankier.vscode-instant-markdown
  - donjayamanne.python
  - freakypie.code-python-isort
  - joelday.docthis
  - johnpapa.azure-functions-tools
  - kisstkondoros.vscode-codemetrics
  - ms-vscode.azure-account
  - msjsdiag.debugger-for-chrome
  - nodesource.vscode-for-node-js-development-pack
  - robertohuertasm.vscode-icons
  - wix.vscode-import-cost
