- name: Set system defaults
  script: set-defaults.sh
  changed_when: false

- name: Install mac-specific homebrew packages
  homebrew: name={{item}} state=latest
  with_items: '{{osx_homebrew_packages}}'

- name: Install Mac apps with homebrew cask
  homebrew_cask: name={{item}} state=present
  with_items: '{{osx_cask_packages}}'

- name: Install mas
  homebrew: name=mas state=latest

- name: Install Mac-App-Store-only apps with mas
  command: mas install {{item}}
  with_items: '{{osx_mas_packages}}'
