# Git repo URL
# The only required argument. Some examples:
#repo: "git@github.com:some_user/some_repo.git"
#repo: "https://github.com/some_user/some_repo.git"
#repo: "git@bitbucket.org:some_user/some_repo.git"

# Directory to clone the repo.
# Default: repo name.
dir: "{{ repo.split('/')[-1].split('.')[0] }}"

# Root directory for the repo.
# Default: project root defined in group_vars/local
root: "{{ project_root }}"

# By default, the virtualenv name is the same as the directory name
env: "{{ dir }}"

# Update the git repo
update: no

# Python version for the pyenv virtualenv
# If the version is not informed, a virtualenv will not be created
python_version: ""

# Versions set by the "pyenv local" command (after the repo's virtualenv)
local: ""

# Directory containing .link files that will become symbolic links in the project root
symlink_dir: ""

# Command to use to install modules in this virtualenv. E.g.:
# - poetry install
# - pipenv install --dev --pre
# - pip install -r requirements.txt
install_command: ""

# Should we run the install command above?
run_install_command: yes
